### ISSUE TITLE
Criar regras e especificações de contribuições

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/privacidade.digital#10]
- [x] Criação do arquivo CODE_OF_CONDUCT.md com Código de Conduta do repositório.
- [ ] Criação do arquivo CONTRIBUTING.md com diretrizes sobre as contribuições.

**Comment by abbluiz** [comment]
Pessoas do Brasil podem se juntar ao time

**Comment by reginildo** [comment]
Podemos usar como referência para esse assunto aqui https://www.contributor-covenant.org/

**Comment by abbluiz** [comment]
> Podemos usar como referência para esse assunto aqui: https://www.contributor-covenant.org/

Vou dar uma olhada. Não sabia que existia esse tipo de padrão.
