### ISSUE TITLE
Corrigir box size de 'Doações' em 'Ferramentas para Privacidade' na página inicial

### ISSUE THREAD

**Issue by ViniciusALS** [PrivacidadeDigital/Privacidade.Digital#12]

**Comment by abbluiz** [comment]
Isso é normal, no site do projeto original também rola da caixa se extender um pouco de acordo com o conteúdo.

**Comment by abbluiz** [comment]
Vou fechar o issue, mas se discordar, reabra.

**Comment by ViniciusALS** [comment]
Eu percebi que no projeto original tambem esta assim. Mas eu acredito que seja realmente um erro de design.

**Comment by ViniciusALS** [comment]
Essse erro tambem se repete em outros cards do site
