### ISSUE TITLE
Traduzir anchor links em todas as páginas

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/privacidade.digital#16]
Exemplo:

https://www.privacidade.digital/sistemas-operacionais/#os

`os` é um anchor link que deve ser traduzido para `so`

**Comment by ViniciusALS** [comment]
@abbluiz ainda falta traduzir algum anchor link ou podemos fechar essa issue?

**Comment by abbluiz** [comment]
> @abbluiz ainda falta traduzir algum anchor link ou podemos fechar essa issue?

Eu não traduzi nenhum ainda

**Comment by abbluiz** [comment]
Traduzido!
