### ISSUE TITLE
Consertar dropbox 'Serviços' no navbar

### ISSUE THREAD

**Issue by ViniciusALS** [PrivacidadeDigital/privacidade.digital#18]
Quando a tela possui entre 1440 a 990 pixels de largura, dropbox fica parcialmente para fora do campo da tela

**Comment by abbluiz** [comment]
Provavelmente relacionado com esse problema do projeto original: https://github.com/privacytoolsIO/privacytools.io/issues/872

**Comment by abbluiz** [comment]
Não tinha percebido isso.

**Comment by abbluiz** [comment]
Acabei de testar

**Comment by abbluiz** [comment]
Acabei de testar e também é um problema do projeto original. Talvez criar um issue lá pra ver se os caras resolvem depois.

**Comment by abbluiz** [comment]
Criei uma issue no projeto original sobre isso: https://github.com/privacytoolsIO/privacytools.io/issues/877

**Comment by abbluiz** [comment]
Problema foi consertado no projeto original e será portado em preve.
