### ISSUE TITLE
Terminar rascunho de tradução completa pra Português do Brasil

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/privacidade.digital#2]
- [x] Página incial (index.html)
- [x] 404.html
- [x] Política de privacidade (privacy-policy.html)
- [x] Arquivos de configuração

- [x] card.html
- [x] footer.html
- [x] head.html
- [x] nav.html
- [x] panel.html
- [x] scripts.html 

- [x] Páginas sobre navegadores
- [x] Páginas sobre sistemas operacionais
- [x] Páginas sobre provedores
- [x] Páginas sobre serviços
- [ ] Páginas sobre software

**Comment by ViniciusALS** [comment]
Falta traduzir OpenNIC em DNS na pagina sobre provedores

**Comment by abbluiz** [comment]
> Falta traduzir OpenNIC em DNS na pagina sobre provedores

Ah, eu pulei esse card, porque achei a tradução difícil e iria deixar pra #4

**Comment by ViniciusALS** [comment]
ok then

> > Falta traduzir OpenNIC em DNS na pagina sobre provedores
> 
> Ah, eu pulei esse card, porque achei a tradução difícil e iria deixar pra #4

ok then

**Comment by ViniciusALS** [comment]
Dentro de ```software -> Conversa de video e voz```, em "informacoes relacionada", voce acha que devemos traduzir ate o nome do artigo em ingles para portugues?

**Comment by abbluiz** [comment]
Acho que sim, por enquanto. Eu traduzi a maioria. Numa segunda leva de tradução, podemos tentar encontrar substitutos dos artigos em inglês ou ver com os donos dos artigos se é possível traduzi-los.

**Comment by ViniciusALS** [comment]
Esta faltando traduzir apenas "notebooks.html", "Productivity-tools.html" e "self-contained-networks.html"
