### ISSUE TITLE
Centralizar ícones no footer da página

### ISSUE THREAD

**Issue by ViniciusALS** [PrivacidadeDigital/privacidade.digital#20]
Centralizar os icones "CC0/Dominio Publico", "Contato" e "Doacoes" no footer da pagina.

**Comment by abbluiz** [comment]
Esse problema ocorre porque eu comentei uma parte do código no footer. Acho que pode descomentar

**Comment by abbluiz** [comment]
Readicionei o kopimi em https://github.com/PrivacidadeDigital/privacidade.digital/commit/c56ee59ae0bc8e943184d5a6dd54758799c198d2 e os ícones voltaram a ficar centralizados
