### ISSUE TITLE
Link 'Sincronizacao de Calendarios e Contatos' em software no navbar levando para uma pagina 404

### ISSUE THREAD

**Issue by ViniciusALS** [PrivacidadeDigital/privacidade.digital#21]

**Comment by abbluiz** [comment]
https://privacidade.digital/software/calendario-e-contatos/

**Comment by abbluiz** [comment]
No navegador do meu celular, o link leva pra essa página e está funcionando

**Comment by abbluiz** [comment]
O último deploy no site foi no commit https://github.com/PrivacidadeDigital/privacidade.digital/commit/2e2acea354da62c6c4da3505db1afa852ffd017a

**Comment by ViniciusALS** [comment]
Tem razao, eu que fiz besteira na minha versao. Obrigado
