### ISSUE TITLE
Sugestões de melhorias e localização na tradução

### ISSUE THREAD

**Issue by ViniciusALS** [PrivacidadeDigital/privacidade.digital#22]
- [x] Trocar ["Conversa de Vídeo & Voz"](https://www.privacidade.digital/software/chamadas/) por "Chamadas de Vídeo & Voz"
- [x] Trocar ["Encontre um mensageiro de vídeo e voz que suporte completamente ligações com criptografia ponta-a-ponta."](https://www.privacidade.digital/software/chamadas/) por "Encontre uma forma de realizar chamadas de video e voz com criptografia ponta-a-ponta".
- [x] Definir um padrao a ser seguido no site em relacao a traduzir ou nao o nome de artigos em ingles

**Comment by abbluiz** [comment]
Concordo com o título novo, mas a descrição, eu votaria em utilizar encriptação ao invés de criptografia, porque a maioria do site eu já traduzi assim.

**Comment by abbluiz** [comment]
Sobre traduzir títulos de artigo, a maioria já estão traduzidos. Eu diria que idealmente, esses artigos sejam em Português, e talvez role de traduzir parte desse conteúdo.
