### ISSUE TITLE
Adicionar Podcast 'Segurança Legal' aos #resources Informações

### ISSUE THREAD

**Issue by reginildo** [PrivacidadeDigital/privacidade.digital#25]
Gostaria de deixar uma sugestão que poderia ser adicionada ao finalizarmos a tradução inicial. A sugestão seria de adicionar o link de acesso ao podcast **Segurança Legal** visto que acredito que é o que considero que é o que mais se assemelha ao podcast **Security Now** no Brasil. Considero que isso acrescente uma boa fonte de informações às pessoas interessadas no assunto de segurança da informação e muitas das pautas abordadas pelos criadores do podcast girar em torno de privacidade e criptografia. [link](https://www.segurancalegal.com/)

**Comment by abbluiz** [comment]
Legal, vou dar uma olhada nesse podcast, eu não conhecia. Vai ser bom começar a dar dicas com conteúdo em Português!

**Comment by ViniciusALS** [comment]
Eu acho que algo assim, deveria ter prioridade em relacao ao conteudo do projeto original. Pois se trata de um conteudo relevante ao brazil.

**Comment by abbluiz** [comment]
Pelo que entendi, ficaria nos links da página inicial, correto?

**Comment by ViniciusALS** [comment]
Eu estava pensando na mesma coisa. Acho que poderiamos criar um secao para recomendar podcasts, blogs, jornais, canais do youtube...

**Comment by abbluiz** [comment]
No projeto original, isso é feito em resources.html que é incorporado na página inicial. Acho que deixar no início já tem uma boa visibilidade. Talvez fosse legal colocar essa sessão separada dos recursos comuns, mas na minha opinião só quando reunisse mais conteúdo em Português. Por enquanto, outra ideia é estilizar o link com um ícone do Brasil ou algo do tipo

**Comment by abbluiz** [comment]
Por outro lado, a ideia do Privacidade Digital é trazer conteúdo do Brasil por padrão. Isso significa tentar traduzir projetos externos na medida do possível. Então fica a dúvida se convém diferenciar

**Comment by abbluiz** [comment]
@reginildo quer adicionar? Seguindo o padrão já existente de links. A gente resolve as outras questões depois.

**Comment by reginildo** [comment]
> No projeto original, isso é feito em resources.html que é incorporado na página inicial. Acho que deixar no início já tem uma boa visibilidade. Talvez fosse legal colocar essa seção separada dos recursos comuns, mas na minha opinião só quando reunisse mais conteúdo em Português. Por enquanto, outra ideia é estilizar o link com um ícone do Brasil ou algo do tipo.

Concordo com você quando fala em colocar no início acima dos outros. E a questão de estilização de link com uma bandeira do Brasil ou algo do tipo, ficaria mais atrativo para o usuário de lingua portuguesa a clicar no link. Visto que praticamente todos os link de recursos adicionais da página é direcionado para as pessoas que falam inglês.

**Comment by reginildo** [comment]
> @reginildo quer adicionar? Seguindo o padrão já existente de links. A gente resolve as outras questões depois.

Claro =). Estarei fazendo isso assim que possível.

**Comment by abbluiz** [comment]
> > @reginildo quer adicionar? Seguindo o padrão já existente de links. A gente resolve as outras questões depois.
> 
> Claro =). Estarei fazendo isso assim que possível.

Obrigado!
