### ISSUE TITLE
Ajustar pagina de indice para todas as categorias do navbar

### ISSUE THREAD

**Issue by ViniciusALS** [PrivacidadeDigital/privacidade.digital#26]
#### [Edited] - Titulo original: Mudar pagina 'Evite servicos hosdados nos eua' em Provedores 

Ao clicar no link "Evite servicos hospedados nos eua", o usuario e direcionado para o artigo ["Vigilância Global em Massa - Os Quatorze Olhos"](https://www.privacidade.digital/provedores/#ukusa). Alem disso, o topo da pagina possui o titulo ["Provedores"](https://www.privacidade.digital/provedores/) e um indice com links para todos os artigos dentro de provedores.

Eu sugiro que nos remocamos o indice com links, ja que o navbar ja possui esse msm indice de forma melhor localiza por todo o site, ou estao, adicionemos em todas as categorias um indice como esse, para padronizar a sua presenca por todo o site.

Alem disso, a pagina possui 3 artigos, ["Vigilância Global em Massa - Os Quatorze Olhos"](https://www.privacidade.digital/provedores/#ukusa), ["Lei de Divulgação de Chaves"](https://www.privacidade.digital/provedores/#kdl) e ["O que é um \"warrant canary\"?"](https://www.privacidade.digital/provedores/#wc). Sugiro que adicionemos um especifico para todos esses artigos no navbar.

**Comment by abbluiz** [comment]
Essa página fica em Provedores pra explicar que provedores baseados nesses países não são recomendados. A ideia é indicar quais os países ideais para se contratar serviços, por isso há todas essas explicações.

**Comment by abbluiz** [comment]
Sobre o índice, se você reparar tem um card na página inicial que é o de Provedores. Quando a pessoa clica, ela vai pro índice de provedores.

**Comment by abbluiz** [comment]
Isso também tem pra software, se não me engano

**Comment by abbluiz** [comment]
Eu acho sua sugestão válida. Eu pensaria em adicionar outro menu no navbar com esses artigos, algo como "Vigilância" e um submenu com essas opções. Porém eu gosto do índice e acho necessário pelo fato dos usuários clicarem da página inicial e irem pra ele.

**Comment by abbluiz** [comment]
E embaixo do índice, talvez linkar com esses artigos, pq a referência é importante

**Comment by ViniciusALS** [comment]
Voce esta certo, software tambem possui esse indice, porem fica em uma pagina separada exclusiva para o indice. Acho que deviamos fazer o mesmo para todas as paginas

**Comment by abbluiz** [comment]
Sistemas Operacionais e Navegadores não tem esse índice porque não existem tantas subcategorias nessas páginas quanto Provedores e Software

**Comment by abbluiz** [comment]
Inclusive, tudo de SO por exemplo, fica numa página só. Os links do navbar apontam pra anchor links dentro da página de SO, e mesma coisa os Navegadores

**Comment by ViniciusALS** [comment]
Novo modelo com indice em todas as categorias sugerido no branch issue#26

**Comment by abbluiz** [comment]
Eu concordo com as alterações. acho que ficou de um jeito mais claro pro usuário e padronizado, sem alterações muito radicais pra quando der merge com o projeto original.
