### ISSUE TITLE
Implementar temas dark e black

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/privacidade.digital#3]
Implementar temas escuros pro site. Ideias:
- Sombrio: tema escuro padrão.
- Noite: tema escuro com cores para não doer o olho.
- Preto: tema totalmente preto para telas OLED.

**Comment by ViniciusALS** [comment]
Eu acho que as cores amarelo e verde claro do logo nao vao funcionar muito bem em um tema dark

**Comment by abbluiz** [comment]
Essa funcionalidade já foi implementada no projeto original. Em breve o nosso também será atualizado com elas.
