### ISSUE TITLE
Pagina de Contato faz referencia ao projeto original

### ISSUE THREAD

**Issue by ViniciusALS** [PrivacidadeDigital/privacidade.digital#30]
A [pagina de contato](https://www.privacidade.digital/contato/) faz referencia ao projeto original dando referencia aos emails, redes sociais, github, e perfil do time do projeto original.

**Comment by abbluiz** [comment]
Agora, a página de contatos faz referência ao chat Matrix e GitHub do projeto em Português. Em breve o email contato@privacidade.digital estará disponível na branch master, pois já foi adicionado em https://github.com/PrivacidadeDigital/privacidade.digital/commit/83633fc34096263510d039ce1c1af267cf56b037
