### ISSUE TITLE
✨ Sugestão de Funcionalidade | Criptomoedas a serem aceitas como doação

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/Privacidade.Digital#31]
Quais criptomoedas devemos aceitar como método de doação para o projeto? O projeto original aceita vários, mas não se sabe como é administrado uma quantidade tão diversa de carteiras digitais de criptomoedas.

Como sugestão, acredito que devemos escolher no máximo 3 criptomoedas inicialmente. Bitcoins provavelmente estaria incluso.

**Comment by reginildo** [comment]
Acho que devemos olhar para as principais criptomoedas utilizadas mesmo, como Bitcoin já citada, Litecoin, Ethereum, Bitcoin Cash e Monero. É bom começar com poucas como o @abbluiz falou e caso necessite, nós apliamos a oferta de acordo com o feedback dos usuários.

Dentre as que eu citei sugiro: Bitcoin, Litecoin e Monero. Destas  três a única que eu nunca administrei uma carteira foi a de Litecoin.

**Comment by abbluiz** [comment]
BTC, BCH, LTC, XLM, XMR e DASH agora são aceitas como doação.
