### ISSUE TITLE
Implementar twitter API para exibir posts

### ISSUE THREAD

**Issue by ViniciusALS** [PrivacidadeDigital/privacidade.digital#32]
Ja que a nossa pagina do twitter agora possui uma leve movimentacao constante de posts, poderiamos implementar a API do twitter no site para exibir os ultimos posts da pagina.

**Comment by abbluiz** [comment]
## Só para constar

Foi decidido que é melhor criar posts numa plataforma adequada no futuro, e usar o Twitter só para divulgar tais posts.

APIs de integração do Twitter tem grandes chances de conter muitos rastreadores

Plataformas de exemplo: blog no site ou Mastodon
