### ISSUE TITLE
Converter preço dos serviços de VPN para BRL

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/privacidade.digital#34]
Atualmente está em EUR e USD.

https://www.privacidade.digital/provedores/vpn/

**Comment by reginildo** [comment]
Estou com dúvida se podemos fazer isso, pois, acredito eu, essas cobranças não são feitas em BRL. Estaríamos apenas dando uma noção de custo final ao usuário. No fim das contas ele teria que pagar esses serviços nessas outras moedas. Também tem a constante variação de preços dessas moedas em relação ao Real Brasileiro, que sempre está valendo cada vez menos. =(

**Comment by abbluiz** [comment]
> Estou com dúvida se podemos fazer isso, pois, acredito eu, essas cobranças não são feitas em BRL. Estaríamos apenas dando uma noção de custo final ao usuário. No fim das contas ele teria que pagar esses serviços nessas outras moedas. Também tem a constante variação de preços dessas moedas em relação ao Real Brasileiro, que sempre está valendo cada vez menos. =(

Verdade. Estarei fechando esta issue por enquanto, pois ja esta antiga e, a menos que outra pessoa discorde, nao faz tanto sentido fazer essa conversao.
