### ISSUE TITLE
Refinamento da tradução em Português do Brasil

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/privacidade.digital#4]
As páginas do site serão revisadas e os tradutores envolvidos irão consertar possíveis erros e melhorar a tradução.

- [x] Página inicial

- [x] Página de contatos

- [x] Página de doações

- [x] Política de privacidade

- [x] Tudo relacionado a navegadores de internet

- [x] Tudo relacionado a sistemas operacionais

- [x] Tudo relacionado a provedores de serviços

- [x] Tudo relacionado a recomendação de softwares

- [x] Outras páginas e documentos

**Comment by ViniciusALS** [comment]
Melhorar traducao de "SO Live CD" em navbar e ["Sistemas Operacionais Live CD"](https://www.privacidade.digital/sistemas-operacionais/#live_os)
