### ISSUE TITLE
✨ Sugestão de Novidade | Criar blog para criar posts sobre o assunto

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/Privacidade.Digital#45]
* CMS necessário para atrair contribuidores
* Melhorar atuação nas redes sociais
* Conteúdo mais aprofundado sobre assuntos postados nas redes sociais

**Comment by reginildo** [comment]
A primeira sugestão que me vem a mente é o _wordpress.com_ pela facilidade de gerenciamento de contribuidores.

**Comment by reginildo** [comment]
> A primeira sugestão que me vem a mente é o _wordpress.com_ pela facilidade de gerenciamento de contribuidores.

Outra sugestão seria criar um blog no github pages.

**Comment by abbluiz** [comment]
Ou ainda, hospedar nosso próprio WordPress ou outra CMS open-source, como ghost.org (mesmo que em blog.privacytools.io).

**Comment by jecogeo** [comment]
Sobre esse ponto, me surgiu uma sugestão: Que o blog seja uma porta de entrada para o site. Para explicar. O site, no meu entedimento, é uma _curadoria_ de ferramentas e opções de serviços que tenham como foco a privacidade do usuário. Isso assume que o visitante já está informado e está procurando alternativas. E é nesse ponto que o site entra: o usuário já está informado e agora precisa encontrar um _hub_ que contenha sugestões confiáveis e sem viéses, como programas de afiliação (e.g. uma VPN está sendo recomendada porque foi analisada, e não porque o provedor pagou para aparecer no site.). Esse é o grande valor da IPD.

Minha sugestão é que o blog seja orientado ao passo anterior desse processo: orientar e educar os visitantes. Por que eu devo parar de usar whatsapp? Por que o modelo de negócio das redes sociais _mainstream_ são um risco para a democracia e para sociedade (por meio da ruptura da privacidade e estabelecimento da vigilância). EM resumo, que o blog seja uma das possíveis "portas de entrada" para o site. Mais um meio de educação que farão os visitantes procurarem alternativas e assim, visitar o site da IPD regularmente.

Nesse sentido, pode-se pensar, inclusive, em um "roteiro" de posts, em que cada post leve à uma seção do site. Um post sobre redes sociais, ao final levaria para a seção correspondente do site. Pode ser que eu esteja "chovendo no molhado" com essa sugestão e que isso já tenha sido pensado. Mas achei interessante expressar essa sugestão de escopo do blog.

**Comment by jecogeo** [comment]
> Ou ainda, hospedar nosso próprio WordPress ou outra CMS open-source, como ghost.org (mesmo que em blog.privacytools.io).

Eu sugeriria hospedar o Write.as, se fosse possível.

**Comment by abbluiz** [comment]
> Sobre esse ponto, me surgiu uma sugestão: Que o blog seja uma porta de entrada para o site. Para explicar. O site, no meu entedimento, é uma _curadoria_ de ferramentas e opções de serviços que tenham como foco a privacidade do usuário. Isso assume que o visitante já está informado e está procurando alternativas. E é nesse ponto que o site entra: o usuário já está informado e agora precisa encontrar um _hub_ que contenha sugestões confiáveis e sem viéses, como programas de afiliação (e.g. uma VPN está sendo recomendada porque foi analisada, e não porque o provedor pagou para aparecer no site.). Esse é o grande valor da IPD.
> 
> Minha sugestão é que o blog seja orientado ao passo anterior desse processo: orientar e educar os visitantes. Por que eu devo parar de usar whatsapp? Por que o modelo de negócio das redes sociais _mainstream_ são um risco para a democracia e para sociedade (por meio da ruptura da privacidade e estabelecimento da vigilância)? Em resumo, que o blog seja uma das possíveis "portas de entrada" para o site. Mais um meio de educação que fará os visitantes procurarem alternativas e assim, visitar o site da IPD regularmente. Nesse sentido, pode-se pensar, inclusive, em um "roteiro" de posts, em que cada post leve à uma seção do site. Um post sobre redes sociais, ao final levaria para a seção correspondente do site.
> 
> Pode ser que eu esteja "chovendo no molhado" com essa sugestão e que isso já tenha sido pensado. Mas achei interessante expressar essa sugestão de escopo do blog para ajudar a orientar as pautas do blog.

É isso mesmo. Na verdade você entrou num assunto que eu não tinha pensando ainda: a possibilidade do blog ser a porta de entrada do site. Eu gosto bastante dessa ideia, mas a primeira coisa que eu pensei seria como isso seria apresentado, por exemplo, eu estou assumindo que nesse caso o blog seria a primeira coisa que o usuário veria ao entrar em Privacidade.Digital, e não a nossa curadoria, certo? 

É possível criar isso diretamente atavés do Jekyll, o que não exigiria quase nenhuma mudança no nosso ciclo de desenvolvimento, o que é interessante, mas ao mesmo tempo blogs Jekyll são mais difíceis para colaboradores futuros. Ou seja, exiria que algum possível convidado escritor do blog teria que entender de Git/GitHub, HTML e possivelmente Jekyll/linha de comando/JavaScript e SCSS.

A ideia inicial era criar algo como um subdomínio como "blog.privacidade.digital" com uma instalação wordpress ou writefreely ou algo do tipo.

**Comment by jecogeo** [comment]
> eu estou assumindo que nesse caso o blog seria a primeira coisa que o usuário veria ao entrar em Privacidade.Digital, e não a nossa curadoria, certo?

Na verdade não pensei nisso. Eu estava pensando mais ou menos alinhado com tua ideia de 
> criar algo como um subdomínio como "blog.privacidade.digital" com uma instalação wordpress ou writefreely

Quando disse que pensava no blog como "porta de entrada" para o site, não quis sugerir que seja a primeira coisa que o visitante veja no site. A tal porta de entrada seria apenas em termos de "processo". Para que o visitante chegue ao site, ele precisa (1) saber porque deveria procurar alternativas e então (2) buscar recomendações confiáveis. 

Existem recursos educativos, notícias, etc, em português, mas pouco ainda. Então a ideia é criar posts que sirvam nesse sentido. O ponto central da minha sugestão é que os posts (ao menos inicialmente) esteja estreitamente linkada com o site, de modo que cada post esteja ligada à uma seção do site. Por exemplo, um post que expõe as fragilidades e quebras de privacidade do Whatsapp, levaria à nossa seção de mensageiros instantâneos. E dessa forma a gente pode ir "guiando" os posts do blog. "Guiando" no seguinte sentido:  _Que seções do privacidade.digital ainda carecem de informações educativas no blog?_. Assim, teremos um set completo de recursos mostrando ao leitor porque ele deve buscar nossas alternativas. Eu acho que isso ajudaria a definir o escopo do blog e ajudaria a orientar e priorizar os assuntos que julgamos importantes. 

Que te parece?

**Comment by abbluiz** [comment]
> > eu estou assumindo que nesse caso o blog seria a primeira coisa que o usuário veria ao entrar em Privacidade.Digital, e não a nossa curadoria, certo?
> 
> Na verdade não pensei nisso. Eu estava pensando mais ou menos alinhado com tua ideia de
> 
> > criar algo como um subdomínio como "blog.privacidade.digital" com uma instalação wordpress ou writefreely
> 
> Quando disse que pensava no blog como "porta de entrada" para o site, não quis sugerir que seja a primeira coisa que o visitante veja no site. A tal porta de entrada seria apenas em termos de "processo". Para que o visitante chegue ao site, ele precisa (1) saber porque deveria procurar alternativas e então (2) buscar recomendações confiáveis.
> 
> Existem recursos educativos, notícias, etc, em português, mas pouco ainda. Então a ideia é criar posts que sirvam nesse sentido. O ponto central da minha sugestão é que os posts (ao menos inicialmente) esteja estreitamente linkada com o site, de modo que cada post esteja ligada à uma seção do site. Por exemplo, um post que expõe as fragilidades e quebras de privacidade do Whatsapp, levaria à nossa seção de mensageiros instantâneos. E dessa forma a gente pode ir "guiando" os posts do blog. "Guiando" no seguinte sentido: _Que seções do privacidade.digital ainda carecem de informações educativas no blog?_. Assim, teremos um set completo de recursos mostrando ao leitor porque ele deve buscar nossas alternativas. Eu acho que isso ajudaria a definir o escopo do blog e ajudaria a orientar e priorizar os assuntos que julgamos importantes.
> 
> Que te parece?

Nesse caso eu concordo 100%, acho que daria pra fazer sim. Podemos começar a pesquisar tipos de instalações de blog que se encaixaria melhor para nós... como eu disse, eu já tinha visto sobre esses:

https://wordpress.org/
https://writefreely.org/
https://ghost.org/
