### ISSUE TITLE
Criar métodos válidos para receber doações em BRL

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/privacidade.digital#5]
Criar carterias de criptomoeda e contas no PayPal e PicPay para receber doações de visitantes brasileiros.

- [ ] PayPal

- [x] PicPay

**Comment by abbluiz** [comment]
Só falta o PayPal, ou já está certo @ViniciusALS?

**Comment by ViniciusALS** [comment]
O paypal esta correto agora e eu ja vou dar push na pagina de doacoes atualizada com ele
