### ISSUE TITLE
Substituir links de artigos em Inglês

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/privacidade.digital#57]
- [x] Indicar quando o link vai para um artigo ou página em Inglês

- [ ] Substituir ou apagar todos os links com artigos em Inglês por artigos em Português, onde necessário

**Comment by reginildo** [comment]
Algo que podemos fazer também é uma versão em português para o argumento "[Não Tenho Nada a Esconder](https://en.wikipedia.org/wiki/Nothing_to_hide_argument)"

**Comment by abbluiz** [comment]
> Algo que podemos fazer também é uma versão em português para o argumento "[Não Tenho Nada a Esconder](https://en.wikipedia.org/wiki/Nothing_to_hide_argument)" no Wikipedia.

Muito boa a ideia. Na Wikipedia mesmo, certo?

**Comment by reginildo** [comment]
@abbluiz Correto. :relaxed:

**Comment by abbluiz** [comment]
> @abbluiz Correto. relaxed

Super apoio. Semana que vem acho que poderei estar ajudando nisso.

**Comment by abbluiz** [comment]
Issue será fechado porque foi indicado os links a artigos em Inglês e outras línguas.
