### ISSUE TITLE
Mostrar no site a última vez que o mesmo foi modificado

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/privacidade.digital#59]
Mostrar no site, provavelmente abaixo do menu de navegação ou no footer, a data e o tempo da última vez que o mesmo foi modificado.

Para tal, será usado a tag Liquid  `site.time`, que indica a última vez que o projeto foi construído no servidor.

**Comment by abbluiz** [comment]
Acredito que seja útil para que o usuário tenha uma noção da veracidade do conteúdo do site. Afinal, caso o projeto demore a ser atualizado, recomendações muito antigas podem comprometer a segurança e privacidade dos visitantes.

**Comment by reginildo** [comment]
É uma boa. Podendo ficar no fim da página.

**Comment by abbluiz** [comment]
> É uma boa. Podendo ficar no fim da página.

Gostei. Menos invasivo do que deixar logo na cara, e mais acessivel por estar no footer.

**Comment by abbluiz** [comment]
Essa funcionalidade foi implemetada na última release do site! Vou fechar a issue agora.
