### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by fabianski7** [PrivacidadeDigital/Privacidade.Digital#61]
Esse repositório não será mais atualizado conforme o privacytools.io?

Exemplo: a página de e-mail da versão pt-br está desatualizada se comparada com o site em inglês.

**Comment by abbluiz** [comment]
Olá. Ultimamente, eu estava sendo a única pessoa que tem feito esse trabalho, portanto quando eu fico ocupado, o repo fica parado. Eu retomarei, creio que dentro de um mês estará atualizado.

**Comment by fabianski7** [comment]
Não estou com muito tempo livre mas posso ajudar.

**Comment by abbluiz** [comment]
> Não estou com muito tempo livre mas posso ajudar.

Eu já dei uma boa atualizada no Domingo. No entanto, ainda há muito o que fazer. Se você quiser ajudar, pode dar uma olhada e resolver os conflitos que puder na branch https://github.com/PrivacidadeDigital/privacidade.digital/tree/privacytools.io-merge

Daí é só criar um pull request pra eu dar uma olhada. Vou fazendo o mesmo até terminar e dar merge na master e deploy no site.

**Comment by abbluiz** [comment]
Se precisar de ajuda e ainda assim quiser ajudar, manda um email pra mim (meu perfil tem o email)

**Comment by abbluiz** [comment]
Novas instruções de colaboração estão sendo escritas na [wiki do repositório](https://github.com/PrivacidadeDigital/privacidade.digital/wiki).
