### ISSUE TITLE
Navegador Brave 

### ISSUE THREAD

**Issue by MiqueiasBito** [PrivacidadeDigital/Privacidade.Digital#63]
Sugestão: Poderiam fazer uma matéria sobre o Brave. Ele diz ser um navegador focado em segurança e tem até integração nativa com o Tor.

**Comment by abbluiz** [comment]
Oi, Miqueias. Valeu pela sugestão!

Nós costumávamos indicar o Brave, mas nós paramos de indicá-lo, pois além do projeto ser experimental e não ser muito estável, o PrivacyTools (site fonte que traduzimos para Privacidade.Digital) decidiu não o recomendar. Um dos motivos é pelo fato de sua existência não ser muito justificada, pelo fato de que você utilizar o Firefox e o navegador Tor se quiser as mesmas funcionalidades do Brave, além de ter ocorrido alguns problemas como o time do Brave "pedir" para serem indicados.

Sobre fazer uma matéria sobre o assunto, temos planos de abrir um blog, mas no momento nosso site é estático. Definitivamente manterei sua ideia em mente quando e se abrirmos um blog.

Sobre a remoção do Brave do PrivacyTools (e consequentemente do Privacidade Digital): https://github.com/privacytools/privacytools.io/pull/1169

Sobre a criação de um blog para o Privacidade Digital: https://github.com/PrivacidadeDigital/privacidade.digital/issues/45
