### ISSUE TITLE
Criar redes sociais e colocar no site

### ISSUE THREAD

**Issue by abbluiz** [PrivacidadeDigital/privacidade.digital#7]
Possíveis redes sociais:

- [x] Twitter

- [ ] Instagram

**Comment by abbluiz** [comment]
Redes sociais criadas no Instagram e Twitter:

* @privacidade.digital no Instagram
* @PrivacidadeJa no Twitter

Ainda não se sabe o que fazer nessas contas, então não serão adicionadas no site ainda

**Comment by reginildo** [comment]
> Redes sociais criadas no Instagram e Twitter:
> 
>     * @privacidade.digital no Instagram
> 
>     * @PrivacidadeJa no Twitter
> 
> 
> Ainda não se sabe o que fazer nessas contas, então não serão adicionadas no site ainda

Pode ser usado para informar uma adição ou remoção de algum software/solução no site e uma rápida explicação do motivo.

**Comment by abbluiz** [comment]
O Twitter está sendo usado para alguns anúncios de acontecimentos relacionados a privacidade, mas sem muita frequência ainda e o Instagram ainda parado

**Comment by abbluiz** [comment]
Twitter deverá ser colocado no site em breve.

**Comment by abbluiz** [comment]
Twitter colocado no site!

**Comment by abbluiz** [comment]
Não vejo motivo suficientemente grande para usar o Instagram no momento. Irei fechar a issue, por enquanto.
